### PR TITLE
Bugfix/blacksmith

### PR DESCRIPTION
**Pull request by AlfredBroda**
Fixes missing forge/anvil requirements for weapons and ingots, brings some item requirements in line with the majority.

### CODE REVIEW

**Comment by Thahat** [comment]
No longer needed because ACE's fix has been pushed.
what item requirements did you change though? those might be interesting to implement!

**Comment by AlfredBroda** [comment]
The equalisation was in this commit, just a single iron sword that is useless to level 4 blacksmiths that have access to better steel stuff at that stage.
https://github.com/Thahat/nordlingmod/pull/5/commits/62d8aa2325de874358f8524061c3100ce951ee6b
I'm going through the files and found some other minor stuff (training dummy for example), will put it all together and make a PR.

**Comment by Thahat** [comment]
Training dummy? I don't have one of those (fiddled with one at some point but never made it build able)

**Comment by AlfredBroda** [comment]
That might be from ACE now that I think about it... Anyway, you can't place it even after you craft it, because of a limit that is 0 at the time (even though I had plenty of footmen eligible for training around). The problem with crafting the dummy on the other hand was (as with a few other cases too), that you can craft something at level X, but you don't have a workstation that needs level X+1 for example - that is a bit of a nuisance to me.

**Comment by Thahat** [comment]
yeah thats mostly ace, though i took your suggestion and changed the iron sword to be craftable one level earlier. currently im working on making the nordling weapons also gain the abillities from the ACE weapons when ace is around. (and fixing up my tags)

**Pull request closed without merging**
